# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1At1VettIZEKIMPUeWUAPx70NOJ99DT21
"""

import streamlit as st
import random

st.title('Test streamlit')
st.write('Hello Worldd!')

if st.button ('Generate Random Number'):
    random_number = random.randint(1,100)
    st.write(f'Random Number: {random_number}')